version: '3'

services:
###> doctrine/doctrine-bundle ###
  database:
    image: mysql:5.7
    working_dir: /var/www/snippet-app
    environment:
      - MYSQL_USER=dev
      - MYSQL_PASSWORD=pass
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=snippet_db
    ports:
      - "3306:3306"
    volumes:
      - .:/var/www/snippet-app

  php-fpm:
    build: docker/php
    working_dir: /var/www/snippet-app
    volumes:
      - '.:/var/www/snippet-app'
    depends_on:
      - database

  nginx:
    image: nginx:alpine
    working_dir: /var/www/snippet-app
    volumes:
      - .:/var/www/snippet-app
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - '80:80'
    depends_on:
      - php-fpm

  db-admin:
    image: adminer
    container_name: dbadmin
    restart: always
    ports:
      - "8081:8080"